import type { EnrichedAction } from "@/lib/actions/resolve";
import { AnswerGallery } from "@/components/chat/AnswerGallery";
import { InlineMarkdown } from "@/components/chat/InlineMarkdown";

type Props = { action: Extract<EnrichedAction, { type: "SHOW_EXPERIENCE" }> };

/**
 * Every real entry from knowledge/experience.md, in the order it's
 * authored there — resolved server-side (lib/actions/timeline.ts), not
 * generated by the model.
 */
export function ShowExperienceAction({ action }: Props) {
  const entries = action.experienceEntries ?? [];

  if (entries.length === 0) {
    return (
      <div className="rounded-xl border border-border border-l-2 border-l-accent bg-surface px-4 py-3 text-sm">
        <p className="font-mono text-xs uppercase tracking-wide text-accent">Experience</p>
        <p className="mt-1 text-muted">Nothing on file yet.</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-3">
      {entries.map((entry) => (
        <div
          key={entry.id}
          className="rounded-xl border border-border border-l-2 border-l-accent bg-surface px-4 py-3 text-sm"
        >
          <div className="flex flex-wrap items-baseline justify-between gap-x-3 gap-y-1">
            <h3 className="font-semibold text-foreground">{entry.title}</h3>
            {entry.dateLabel && (
              <span className="shrink-0 font-mono text-xs text-muted">{entry.dateLabel}</span>
            )}
          </div>
          {entry.body && (
            <p className="mt-1.5 whitespace-pre-wrap text-muted">
              <InlineMarkdown text={entry.body} />
            </p>
          )}
          {entry.images.length > 0 && (
            <AnswerGallery images={entry.images} label={entry.title} />
          )}
        </div>
      ))}
    </div>
  );
}
